# Generated by Django 3.2.9 on 2021-12-16 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'distributer',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'please enter the name', 'unique': 'the value is not unique'}, help_text='Please enter a unique name!', max_length=20, validators=[products.models.check_for_phone])),
                ('slug', models.SlugField(unique=True)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('is_availible', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('COM', 'Computer'), ('CAM', 'Camera'), ('PHN', 'Phone')], max_length=250)),
                ('distributers', models.ManyToManyField(to='products.Distributer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product',
                'ordering': ['-price', 'created'],
            },
        ),
    ]
