# Generated by Django 3.2.9 on 2021-11-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_availible',
            field=models.BooleanField(default=True),
        ),
    ]
