# Generated by Django 3.2.9 on 2021-12-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='distributers',
            field=models.ManyToManyField(blank=True, null=True, to='products.Distributer'),
        ),
    ]
