# Generated by Django 3.2.9 on 2021-12-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_distributers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='distributers',
            field=models.ManyToManyField(to='products.Distributer'),
        ),
    ]
