# Generated by Django 3.2.9 on 2021-11-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
