# Generated by Django 3.2.9 on 2021-11-28 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-price', 'created']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='update',
            new_name='updated',
        ),
    ]
