# Generated by Django 3.2.9 on 2021-11-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'distributer',
            },
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='product',
            name='distributers',
            field=models.ManyToManyField(to='products.Distributer'),
        ),
    ]
