# Generated by Django 3.2.9 on 2021-11-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20211129_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('COM', 'Computer'), ('CAM', 'Camera'), ('PHN', 'Phone')], default='COM', max_length=250),
            preserve_default=False,
        ),
    ]
