# Generated by Django 3.2.9 on 2021-12-02 03:16

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=20, unique=True, validators=[products.models.check_for_phone]),
        ),
    ]
